/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoSetsIndexRouteImport } from './routes/demo/sets.index'
import { Route as DemoSetsCategoryIdRouteImport } from './routes/demo/sets.$categoryId'
import { Route as DemoProductsGroupIdRouteImport } from './routes/demo/products.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSetsIndexRoute = DemoSetsIndexRouteImport.update({
  id: '/demo/sets/',
  path: '/demo/sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSetsCategoryIdRoute = DemoSetsCategoryIdRouteImport.update({
  id: '/demo/sets/$categoryId',
  path: '/demo/sets/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProductsGroupIdRoute = DemoProductsGroupIdRouteImport.update({
  id: '/demo/products/$groupId',
  path: '/demo/products/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/products/$groupId': typeof DemoProductsGroupIdRoute
  '/demo/sets/$categoryId': typeof DemoSetsCategoryIdRoute
  '/demo/sets/': typeof DemoSetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/products/$groupId': typeof DemoProductsGroupIdRoute
  '/demo/sets/$categoryId': typeof DemoSetsCategoryIdRoute
  '/demo/sets': typeof DemoSetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/products/$groupId': typeof DemoProductsGroupIdRoute
  '/demo/sets/$categoryId': typeof DemoSetsCategoryIdRoute
  '/demo/sets/': typeof DemoSetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/products/$groupId'
    | '/demo/sets/$categoryId'
    | '/demo/sets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/products/$groupId' | '/demo/sets/$categoryId' | '/demo/sets'
  id:
    | '__root__'
    | '/'
    | '/demo/products/$groupId'
    | '/demo/sets/$categoryId'
    | '/demo/sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoProductsGroupIdRoute: typeof DemoProductsGroupIdRoute
  DemoSetsCategoryIdRoute: typeof DemoSetsCategoryIdRoute
  DemoSetsIndexRoute: typeof DemoSetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sets/': {
      id: '/demo/sets/'
      path: '/demo/sets'
      fullPath: '/demo/sets/'
      preLoaderRoute: typeof DemoSetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sets/$categoryId': {
      id: '/demo/sets/$categoryId'
      path: '/demo/sets/$categoryId'
      fullPath: '/demo/sets/$categoryId'
      preLoaderRoute: typeof DemoSetsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/products/$groupId': {
      id: '/demo/products/$groupId'
      path: '/demo/products/$groupId'
      fullPath: '/demo/products/$groupId'
      preLoaderRoute: typeof DemoProductsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoProductsGroupIdRoute: DemoProductsGroupIdRoute,
  DemoSetsCategoryIdRoute: DemoSetsCategoryIdRoute,
  DemoSetsIndexRoute: DemoSetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
