/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetsIndexRouteImport } from './routes/sets.index'
import { Route as SetsCategoryIdRouteImport } from './routes/sets.$categoryId'
import { Route as ProductsGroupIdRouteImport } from './routes/products.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsIndexRoute = SetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsCategoryIdRoute = SetsCategoryIdRouteImport.update({
  id: '/sets/$categoryId',
  path: '/sets/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGroupIdRoute = ProductsGroupIdRouteImport.update({
  id: '/products/$groupId',
  path: '/products/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$groupId': typeof ProductsGroupIdRoute
  '/sets/$categoryId': typeof SetsCategoryIdRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$groupId': typeof ProductsGroupIdRoute
  '/sets/$categoryId': typeof SetsCategoryIdRoute
  '/sets': typeof SetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$groupId': typeof ProductsGroupIdRoute
  '/sets/$categoryId': typeof SetsCategoryIdRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$groupId' | '/sets/$categoryId' | '/sets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$groupId' | '/sets/$categoryId' | '/sets'
  id: '__root__' | '/' | '/products/$groupId' | '/sets/$categoryId' | '/sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsGroupIdRoute: typeof ProductsGroupIdRoute
  SetsCategoryIdRoute: typeof SetsCategoryIdRoute
  SetsIndexRoute: typeof SetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/': {
      id: '/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof SetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$categoryId': {
      id: '/sets/$categoryId'
      path: '/sets/$categoryId'
      fullPath: '/sets/$categoryId'
      preLoaderRoute: typeof SetsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$groupId': {
      id: '/products/$groupId'
      path: '/products/$groupId'
      fullPath: '/products/$groupId'
      preLoaderRoute: typeof ProductsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsGroupIdRoute: ProductsGroupIdRoute,
  SetsCategoryIdRoute: SetsCategoryIdRoute,
  SetsIndexRoute: SetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
